package me.repeater64.mpkseedfilter.filtering.fortress

enum class PieceType {
    NETHER_FORTRESS_START,
    NETHER_FORTRESS_CASTLE_CORRIDOR_T_BALCONY,
    NETHER_FORTRESS_CASTLE_CORRIDOR_STAIRS,
    NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_LEFT_TURN,
    NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_RIGHT_TURN,
    NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR_CROSSING,
    NETHER_FORTRESS_CASTLE_SMALL_CORRIDOR,
    NETHER_FORTRESS_CASTLE_STALK_ROOM,
    NETHER_FORTRESS_CASTLE_ENTRANCE,
    NETHER_FORTRESS_MONSTER_THRONE,
    NETHER_FORTRESS_STAIRS_ROOM,
    NETHER_FORTRESS_ROOM_CROSSING,
    NETHER_FORTRESS_BRIDGE_CROSSING,
    NETHER_FORTRESS_BRIDGE_STRAIGHT,
    NETHER_FORTRESS_BRIDGE_END_FILLER
}